# macOS .zprofile

## PATH: homebrew > /usr/local > system > ~/bin > golang > lm-studio
# load system PATH in .zprofile, see:
#   https://zsh.sourceforge.io/Doc/Release/Files.html#index-zshenv
#   https://apple.stackexchange.com/questions/388622/zsh-zprofile-zshrc-zlogin-what-goes-where
#   https://apple.stackexchange.com/questions/432226/homebrew-path-set-in-zshenv-is-overridden

# load /etc/manpaths and /etc/manpaths.d/* (from https://gist.github.com/Linerre/f11ad4a6a934dcf01ee8415c9457e7b2)
# requires an explicit call to path_helper
export MANPATH
eval "$(/usr/libexec/path_helper)"

# note: run `sudo /usr/libexec/makewhatis /usr/local/texlive/YEAR/texmf-dist/doc/man` to fix makewhatis error:
# makewhatis: /Library/TeX/Distributions/.DefaultTeX/Contents/Man: Not a directory
# makewhatis: /Library/TeX/texbin/man: Not a directory
# https://unix.stackexchange.com/questions/725018/why-does-makewhatis-choke-on-symbolically-linked-directories-and-how-can-i-fi
# test with `apropos foo`

# add homebrew to environment
if [ -x /usr/local/bin/brew ]
then
	eval "$(/usr/local/bin/brew shellenv)"
elif [ -x /opt/homebrew/bin/brew ]
then
	export PATH="/usr/local/bin:/usr/local/sbin${PATH+:$PATH}"
	eval "$(/opt/homebrew/bin/brew shellenv)"
else
	export PATH="/usr/local/bin:/usr/local/sbin${PATH+:$PATH}"
fi

# init rbenv if present - adapted from `rbenv init`
if /usr/bin/which -s rbenv; then eval "$(rbenv init -)"; fi

# init pyenv if present - adapted from `pyenv init`
if /usr/bin/which -s pyenv
then
	export PYENV_ROOT="$HOME/.pyenv"
	[[ -d "$PYENV_ROOT/bin" ]] && export PATH="$PYENV_ROOT/bin:$PATH"
	eval "$(pyenv init -)"
fi

# add ruby gems
if /usr/bin/which -s brew
then
	RUBY_PREFIX="$(brew --prefix --installed ruby 2>/dev/null)"
	[ -n "$RUBY_PREFIX" ] && GEM_BINDIR="$("$RUBY_PREFIX/bin/ruby" -e 'puts Gem.bindir' 2>/dev/null)"
	[ -d "$GEM_BINDIR" ] && export PATH="$PATH:$GEM_BINDIR"
fi

# add unversioned python
if /usr/bin/which -s brew
then
	PYTHON_PREFIX="$(brew --prefix --installed python 2>/dev/null)"
	[ -d "${PYTHON_PREFIX}/libexec/bin" ] && export PATH="$PATH:${PYTHON_PREFIX}/libexec/bin"
fi
