# macOS .zshrc

## PATH: homebrew > /usr/local > system > ~/bin > golang
# load /etc/manpaths and /etc/manpaths.d/* (from https://gist.github.com/Linerre/f11ad4a6a934dcf01ee8415c9457e7b2)
export MANPATH
eval "$(/usr/libexec/path_helper)"
# note: run `sudo /usr/libexec/makewhatis /usr/local/texlive/2023/texmf-dist/doc/man` to fix makewhatis error:
# makewhatis: /Library/TeX/Distributions/.DefaultTeX/Contents/Man: Not a directory
# makewhatis: /Library/TeX/texbin/man: Not a directory
# https://unix.stackexchange.com/questions/725018/why-does-makewhatis-choke-on-symbolically-linked-directories-and-how-can-i-fi

# remove /usr/local/bin from /etc/paths
export PATH="$PATH:s/\/usr\/local\/bin://"

# add homebrew to environment
if [ -x /usr/local/bin/brew ]
then
	eval "$(/usr/local/bin/brew shellenv)"
elif [ -x /opt/homebrew/bin/brew ]
then
	export PATH="/usr/local/bin:/usr/local/sbin${PATH+:$PATH}"
	eval "$(/opt/homebrew/bin/brew shellenv)"
else
	export PATH="/usr/local/bin:/usr/local/sbin${PATH+:$PATH}"
fi

# add ~/bin
export PATH="$PATH:$HOME/bin"

## development environment
# init rbenv if present - adapted from `rbenv init`
if /usr/bin/which -s rbenv; then eval "$(rbenv init -)"; fi

# init pyenv if present - adapted from `pyenv init`
if /usr/bin/which -s pyenv
then
	export PYENV_ROOT="$HOME/.pyenv"
	export PATH="$PYENV_ROOT/bin:$PATH"
	eval "$(pyenv init -)"
fi

# golang
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# load Github access token (if present)
if [ -f $HOME/.githubtokenrc ]; then . $HOME/.githubtokenrc; fi

## other environment
export PAGER="less -is"
export EDITOR=/usr/bin/vim
export RSYNC_RSH=/usr/bin/ssh

## command line
# improved support for hh from `hh -s`
# HSTR configuration - add this to ~/.zshrc
alias hh=hstr				# hh to be alias for hstr
setopt histignorespace			# skip cmds w/ leading space from history
export HSTR_CONFIG=hicolor		# get more colors
bindkey -s "\C-r" "\C-a hstr -- \C-j"	# bind hstr to Ctrl-r (for Vi mode check doc)
export HSTR_TIOCSTI=y

# support for https://github.com/bamos/zsh-history-analysis
export HISTSIZE=1000000
export SAVEHIST=$HISTSIZE
setopt EXTENDED_HISTORY

# Homebrew options, aliases
if [ -f $HOME/.brewrc ]; then . $HOME/.brewrc; fi
# export HOMEBREW_FORCE_BREWED_CURL=1 # to fix a curl cert error: https://github.com/Homebrew/brew/issues/7667
export HOMEBREW_CLEANUP_MAX_AGE_DAYS=36500 # set to 100 years since permanent is not an option
alias update='brew update && brew outdated --greedy-auto-updates'
alias upgrade='brew upgrade --greedy-auto-updates && brew cleanup'
alias leaves='brew leaves | diff -u ~/bin/`hostname -s`-brew  - ; brew list --cask | diff -u ~/bin/`hostname -s`-cask -'
alias check='brew doctor ; brew bundle check --global --verbose ; brew bundle cleanup --global'
alias cleanup='brew bundle install --global && brew bundle cleanup --global --force && brew cleanup -s'
alias fetch='brew fetch --formula `brew list --formula` && brew fetch --cask `brew list --cask`'

# helpful aliases
alias dir='ls -lAG'
alias psax='ps -axo pid,tt,stat,time,start,user,command'
alias tcpopen='sudo lsof -n -iTCP -sTCP:LISTEN'
alias tcpall='sudo lsof -n -iTCP'
