# macOS .zshrc

## PATH: homebrew > /usr/local > system > ~/bin > golang > lm-studio
# load system PATH in .zprofile, see:
#   https://zsh.sourceforge.io/Doc/Release/Files.html#index-zshenv
#   https://apple.stackexchange.com/questions/388622/zsh-zprofile-zshrc-zlogin-what-goes-where
#   https://apple.stackexchange.com/questions/432226/homebrew-path-set-in-zshenv-is-overridden

# add interactive paths
export PATH="$PATH:$HOME/bin"

# golang
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"

# lm-studio
if [ -d "$HOME/.lmstudio/bin" ]; then export PATH="$PATH:$HOME/.lmstudio/bin"; fi

# load GitHub access token (if present)
if [ -f "$HOME/.githubtokenrc" ]; then . "$HOME/.githubtokenrc"; fi

## other environment
export PAGER='less -is'
export EDITOR=/usr/bin/vim
export RSYNC_RSH=/usr/bin/ssh

## command line
# improved support for hh from `hh -s`
# HSTR configuration - add this to ~/.zshrc
alias hh=hstr				# hh to be alias for hstr
setopt histignorespace			# skip cmds w/ leading space from history
export HSTR_CONFIG=hicolor		# get more colors
export HSTR_TIOCSTI=y

# support for https://github.com/bamos/zsh-history-analysis
export HISTSIZE=1000000
export SAVEHIST="$HISTSIZE"
setopt EXTENDED_HISTORY

# Homebrew options, aliases
if [ -f "$HOME/.brewrc" ]; then . "$HOME/.brewrc"; fi
# export HOMEBREW_FORCE_BREWED_CURL=1 # to fix a curl cert error: https://github.com/Homebrew/brew/issues/7667
export HOMEBREW_CLEANUP_MAX_AGE_DAYS=36500 # set to 100 years since permanent is not an option
alias update='brew update && brew outdated --greedy-auto-updates'
alias upgrade='brew upgrade --greedy-auto-updates && brew cleanup'
alias leaves='brew leaves | diff -u ~/bin/$(hostname -s)-brew - ; brew list --cask | diff -u ~/bin/$(hostname -s)-cask -'
alias check='brew doctor ; brew bundle check --global --verbose ; brew bundle cleanup --global'
alias cleanup='brew bundle install --global && brew bundle cleanup --global --force && brew cleanup -s'
alias fetch='brew fetch --formula $(brew list --formula) && brew fetch --cask $(brew list --cask)'

# helpful aliases
alias dir='ls -lAG'
alias psax='ps -axo pid,tt,stat,time,start,user,command'
alias tcpopen='sudo lsof -n -iTCP -sTCP:LISTEN'
alias tcpall='sudo lsof -n -iTCP'
