#!/bin/sh
if ! /usr/bin/which -s rig; then exit; fi

LATEST=$(rig resolve release --json | jq -r '.[-1].version')
GLOBAL=$(rig list --json | jq -r '.[-1].version')
NEWVER="${LATEST%.*}-$(uname -m)"

if [ "$GLOBAL" = "$LATEST" ]
then
	exit 0
else
	printf "installed R version (%s) does not match latest version (%s)\n" "$GLOBAL" "$LATEST"
	printf "to install:\n  rig install --without-pak %s && rig default %s\n" "$LATEST" "$NEWVER"
	printf "post-install:\n"
	printf "  sudo chown -R \`whoami\`:admin /Library/Frameworks/R.framework/Versions/%s/Resources/library\n\n" "$NEWVER"
	printf "rig install --without-pak %s && rig default %s && sudo chown -R \`whoami\`:admin /Library/Frameworks/R.framework/Versions/%s/Resources/library" "$LATEST" "$NEWVER" "$NEWVER" | pbcopy
	exit 1
fi
