#!/bin/sh
if ! /usr/bin/which -s rbenv; then exit; fi

LATEST=`rbenv install -l | grep '^\d' | tail -1`
GLOBAL=`rbenv global`

if [ "x${GLOBAL}" == "x${LATEST}" ]
then
	exit 0
else
	echo "installed ruby version (${GLOBAL}) does not match latest version (${LATEST})"
	echo "to install:\n  rbenv install ${LATEST} && rbenv global ${LATEST}"
	echo "or:\n  brew rbenv-sync && rbenv global ${LATEST}\n"
	exit 1
fi
