#!/bin/sh
LATEST=`pyenv latest -k 3`
GLOBAL=`pyenv global`

if [ "x${GLOBAL}" == "x${LATEST}" ]
then
	exit 0
else
	echo "installed python version (${GLOBAL}) does not match latest version (${LATEST})"
	echo "to install:\n  pyenv install ${LATEST} && pyenv global ${LATEST}"
	echo "or:\n  brew pyenv-sync && pyenv global ${LATEST}\n"
	exit 1
fi
