#!/bin/sh
# set -ex # halt script on error, echo on

link() {
	source="${1}"
	target="${2}"

	if [ ! -e "${target}" ]
	then
		ln -s "${source}" "${target}"
	fi
}

cd "$HOME"/bin/dotfiles || exit
for f in *
do
	link bin/dotfiles/"$f" "$HOME"/."$f"
done

# R install
mkdir "$HOME"/.R
link ../bin/R/Makevars "$HOME"/.R/Makevars
